// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gocffqyqeunanqjzenek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvY2ZmcXlxZXVuYW5xanplbmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MjI0NzgsImV4cCI6MjA1NjQ5ODQ3OH0.NCWfOQO_WFU6kUKtUgmtqUjVpAK_ZlwJqwJPehjcAFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);